[package]
name = "ips-patcher"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = "3.10.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.clap]
version = "4.5.6"
features = ["cargo"]
